spring:
  datasource:
    url: jdbc:mysql://localhost:3366/identity_service
    username: root
    password: Bom474002
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /identity-service
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
jwt:
  signature: _qTEDoz-q--3HrDZ8pUN_iodq47T3tyoZ02vDEkYSzlq_Wo676Ph2fA5HJtkkMYez_U6kYqnHFuV2tpKigEOaw
  expiration: 20
  refresh:
    expiration: 120
app:
  service:
    profile: http://localhost:8082/profile-service