spring:
  application:
    name: social
  cloud:
    gateway:
      routes:
      - id: identity-service
        uri: http://localhost:8081
        predicates:
        - Path=${app.api-prefix}/identity-service/**
        filters:
        - StripPrefix=2
      - id: profile-service
        uri: http://localhost:8082
        predicates:
        - Path=${app.api-prefix}/profile-service/profiles/**
        filters:
        - StripPrefix=2
app:
  api-prefix: /api/v1